apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: playground
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 30081
        hostPort: 30081
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 30082
        hostPort: 30082
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 30083
        hostPort: 30083
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 30084
        hostPort: 30084
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 30085
        hostPort: 30085
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 30443
        hostPort: 30443
        listenAddress: "0.0.0.0"
        protocol: TCP
  - role: worker
  - role: worker
