CREATE TABLE IF NOT EXISTS INVENTORIES (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `INVENTORY_ID` VARCHAR(255) NOT NULL,
    `GOLD_AMOUNT` INT NOT NULL,

    PRIMARY KEY(ID),
    UNIQUE KEY(INVENTORY_ID)
);
