CREATE TABLE IF NOT EXISTS CHARACTERS (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `CHARACTER_ID` VARCHAR(255) NOT NULL,
    `LOGIN_ID` VARCHAR(255) NOT NULL,
    `NICKNAME` VARCHAR(255) NOT NULL,
    `CLASS` ENUM('MAGE', 'WARRIOR', 'RANGER') NOT NULL,
    `INVENTORY_ID` VARCHAR(255) NOT NULL,
    `GUILD_ID` VARCHAR(255) NOT NULL,
    `VAULT_ID` VARCHAR(255) NOT NULL,

    PRIMARY KEY(ID),
    FOREIGN KEY(INVENTORY_ID) REFERENCES INVENTORIES(INVENTORY_ID),
    UNIQUE KEY(CHARACTER_ID)
);

