CREATE TABLE IF NOT EXISTS PLAYER_ITEMS (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PLAYER_ITEM_ID` VARCHAR(255) NOT NULL,
    `ITEM_ID` VARCHAR(255) NOT NULL,
    `DESCRIPTION` VARCHAR(255) NOT NULL,
    `QUANTITY` INT NOT NULL,
    `INVENTORY_ID` VARCHAR(255) NOT NULL,

    PRIMARY KEY(ID),
    FOREIGN KEY(INVENTORY_ID) REFERENCES INVENTORIES(INVENTORY_ID) ON DELETE CASCADE, 
    UNIQUE KEY(PLAYER_ITEM_ID)
);