CREATE VIEW VW_INVENTORY_ITEMS AS
SELECT
    i.INVENTORY_ID,
    i.GOLD_AMOUNT,
    pi.PLAYER_ITEM_ID,
    pi.ITEM_ID,
    pi.DESCRIPTION,
    COALESCE(pi.QUANTITY, 0) AS QUANTITY
FROM INVENTORIES i
LEFT JOIN PLAYER_ITEMS pi ON i.INVENTORY_ID = pi.INVENTORY_ID;