services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.2.4
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]
    ports:
      - "7080:7080"
      - "7443:7443"
    networks:
      - local_network
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=character-db
      - MYSQL_ROOT_PASSWORD=mysqlPW
      - MYSQL_USER=character
      - MYSQL_PASSWORD=characterPW
    ports:
      - '3306:3306'
    networks:
      - db

networks:
  local_network:
    driver: bridge
  db:
    driver: bridge